### ISSUE TITLE
Import SSL certificate

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-test-setup-abstraction-java#25]
Currently, the ETAJ just trusts all certificates since the Exasol cluster uses a self-signed certificate. In the future we could replace this by importing the certificate of the Exasol-Cluster. 

Possible problem: Since we tunnel the connection via a SSH-tunnel, the hostname changes. --> The certificate validation might fail.

**Comment by redcatbear** [comment]
Shelved.
