### ISSUE TITLE
Builder pattern for ExasolTestSetupFactory 

### ISSUE THREAD

**Issue by ckunki** [exasol/exasol-test-setup-abstraction-java#47]
`standaloneConfig` is current required parameter in constructor 

Proposal: 
* use a builder 
* make `standaloneConfig` optional
* if `standaloneConfig` is not specified then use `ExasolTestcontainerTestSetup`
* if `standaloneConfig` is specified then require file to exist and use `StandaloneExasolTestSetup`

**Comment by redcatbear** [comment]
I just checked the class in question. It has only this one optional field. That's a little bit thin for a builder. I would suggest to use an additional constructor with no parameters and add the assertion that the config file exists to the existing constructor.
