### ISSUE TITLE
Support user provided Exasol docker-db version

### ISSUE THREAD

**Issue by morazow** [exasol/exasol-test-setup-abstraction-java#62]
### Situation

ETAJ should use the user provided Exasol docker version. When running CI or locally, we usually set the docker-db versions (e.g, as environment variable). It would help if the ETAJ uses this version of docker-db.

For example the one set by the `com.exasol.dockerdb.image` parameter:

```
-Dcom.exasol.dockerdb.image=${{ matrix.docker_db_version }}
```

### Acceptance Criteria

- Uses user provided docker-db version

**Comment by kaklakariada** [comment]
exasol-test-setup-abstraction-java delegates to exasol-testcontainers which in turn uses system property `com.exasol.dockerdb.image`. So setting this system property will allow the user to define the Exasol DB version to use.
Ci build uses this mechanism to test with Exasol 7.1 and 8.
We also use this in https://github.com/exasol/exasol-test-setup-abstraction-server/blob/main/go-client/server.go#L24-L32

Closing as already implemented.
