### ISSUE TITLE
Wait for DB container to be extracted

### ISSUE THREAD

**Issue by ckunki** [exasol/exasol-test-setup-abstraction-java#66]
Currently ETAJ does not wait for the script language container contained in the Exasol database (< version 8) to be extracted. 

This can take ~ 5 minutes, and hence ETC offers method `waitUntilContainerStarted()` in [ExasolContainer line L530](https://github.com/exasol/exasol-testcontainers/blob/164007f5e996027ab2a0486b6a13f6e4e4ff948c/src/main/java/com/exasol/containers/ExasolContainer.java#L530), but ETAJ does not call this method. 

This led to problems while working on [KCE issue #72](https://github.com/exasol/kafka-connector-extension/issues/72).

### Acceptance Criteria 

[ETAJ, ExasolTestcontainerTestSetup line 25](https://github.com/exasol/exasol-test-setup-abstraction-java/blob/03ea85c8656059833f6f3082705b77dadeae1188/src/main/java/com/exasol/exasoltestsetup/testcontainers/ExasolTestcontainerTestSetup.java#L25) does not specify any services, e.g. UDF, BucketFS, ...
Therefore ETC would not wait for SLC to be extracted even when asked for.

Proposal: 
1. enhance ETAJ to require all services by default and call method `waitUntilContainerStarted()` unconditionally. 

Note: As mentioned by @tkilias Docker Containers for Exasol DB version 8 and higher are probably not affected as these are using a container format with SLC contents already extracted, not requiring additional extraction.

**Comment by ckunki** [comment]
When looking at @pj-spoelders' log files we identified that SLC had already been extracted:
Log file `/exa/logs/cored/bucketfsd.*.log` contained a line matching regular expression `"ScriptLanguages.*extracted$"` as [exasol-testcontainers / UdfContainerWaitStrategy](https://github.com/exasol/exasol-testcontainers/blob/164007f5e996027ab2a0486b6a13f6e4e4ff948c/src/main/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategy.java) searches for. 

So currently we assume a different issue and propose to 
1. setup [script logging](https://docs.exasol.com/db/latest/database_concepts/virtual_schema/logging.htm) 
2. run the SQL statements again, e.g. with an SQL client such as DBeaver 
3. inspect output of `nc`

**Comment by redcatbear** [comment]
@ckunki is this ticket still valid? I read your last comment as a "no".

**Comment by kaklakariada** [comment]
I propose to add `.withRequiredServices(ExasolService.BUCKETFS, ExasolService.JDBC, ExasolService.UDF)` when starting the container. This ensures that it waits until the SLC is extracted.
