### ISSUE TITLE
Startup fails for Exasol DB version 8.25.0

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-test-setup-abstraction-java#75]
When using Exasol Docker DB version 8.25.0, constructor call `new ExasolTestcontainerTestSetup()` fails with the following exception:
```
java.lang.IllegalStateException: E-ETAJ-12: Failed to ssh to the exasol database. This is required for redirecting a host port. Known mitigations:
* Make sure the database is reachable, i.e. port 32784 open on host '192.168.56.6'.
* Make sure user 'root' can login to the database using your ssh-key.
 at com.exasol.exasoltestsetup.SshConnection.createSession([SshConnection.java:47](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.exasol.exasoltestsetup.SshConnection.([SshConnection.java:31](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.exasol.exasoltestsetup.testcontainers.ExasolTestcontainerTestSetup.([ExasolTestcontainerTestSetup.java:43](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.exasol.exasoltestsetup.testcontainers.ExasolTestcontainerTestSetupIT.getExasolTestSetup([ExasolTestcontainerTestSetupIT.java:10](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.exasol.exasoltestsetup.ExasolTestSetupTestBase.beforeEach([ExasolTestSetupTestBase.java:41](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1541](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1541](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
 at com.jcraft.jsch.Session.receive_kexinit([Session.java:590](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.jcraft.jsch.Session.connect([Session.java:320](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.jcraft.jsch.Session.connect([Session.java:183](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.exasol.exasoltestsetup.SshConnection.createSession([SshConnection.java:39](vscode-file://vscode-app/Users/chp/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 7 more
```

## Workaround
Use Exasol DB 8.24.0

**Comment by ckunki** [comment]
effort .1 pd from my side

**Comment by kaklakariada** [comment]
After enabling log level debug for the ssh server it logs the following error:

```
Apr 15 14:44:42 n11 sshd[12282]: Unable to negotiate with 172.17.0.1 port 60756: no matching host key type found. Their offer: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 [preauth]
```

<details>
<summary>Complete log</summary>
<pre>
Apr 15 14:44:42 n11 sshd[2810]: debug3: fd 5 is not O_NONBLOCK
Apr 15 14:44:42 n11 sshd[2810]: debug1: Forked child 12282.
Apr 15 14:44:42 n11 sshd[2810]: debug3: send_rexec_state: entering fd = 8 config len 3256
Apr 15 14:44:42 n11 sshd[2810]: debug3: ssh_msg_send: type 0
Apr 15 14:44:42 n11 sshd[2810]: debug3: send_rexec_state: done
Apr 15 14:44:42 n11 sshd[12282]: debug3: oom_adjust_restore
Apr 15 14:44:42 n11 sshd[12282]: debug1: Set /proc/self/oom_score_adj to 0
Apr 15 14:44:42 n11 sshd[12282]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Apr 15 14:44:42 n11 sshd[12282]: debug1: inetd sockets after dupping: 4, 4
Apr 15 14:44:42 n11 sshd[12282]: Connection from 172.17.0.1 port 60756 on 172.17.0.3 port 22 rdomain ""
Apr 15 14:44:42 n11 sshd[12282]: debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
Apr 15 14:44:42 n11 sshd[12282]: debug1: Remote protocol version 2.0, remote software version JSCH-0.1.54
Apr 15 14:44:42 n11 sshd[12282]: debug1: compat_banner: no match: JSCH-0.1.54
Apr 15 14:44:42 n11 sshd[12282]: debug2: fd 4 setting O_NONBLOCK
Apr 15 14:44:42 n11 sshd[12282]: debug3: ssh_sandbox_init: preparing seccomp filter sandbox
Apr 15 14:44:42 n11 sshd[12282]: debug2: Network child is on pid 12283
Apr 15 14:44:42 n11 sshd[12282]: debug3: preauth child monitor started
Apr 15 14:44:42 n11 sshd[12282]: debug3: privsep user:group 102:65534 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: permanently_set_uid: 102/65534 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: ssh_sandbox_child: setting PR_SET_NO_NEW_PRIVS [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: ssh_sandbox_child: attaching seccomp filter program [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: append_hostkey_type: ssh-rsa key not permitted by HostkeyAlgorithms [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: send packet: type 20 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: receive packet: type 20 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: SSH2_MSG_KEXINIT received [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: local server KEXINIT proposal [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: compression ctos: none,zlib@openssh.com [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: compression stoc: none,zlib@openssh.com [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: languages ctos:  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: languages stoc:  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: first_kex_follows 0  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: reserved 0  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: peer client KEXINIT proposal [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: host key algorithms: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: ciphers ctos: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: ciphers stoc: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: MACs ctos: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: MACs stoc: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: compression ctos: none [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: compression stoc: none [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: languages ctos:  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: languages stoc:  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: first_kex_follows 0  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug2: reserved 0  [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: kex: host key algorithm: (no match) [preauth]
Apr 15 14:44:42 n11 sshd[12282]: Unable to negotiate with 172.17.0.1 port 60756: no matching host key type found. Their offer: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: do_cleanup [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug3: PAM: sshpam_thread_cleanup entering [preauth]
Apr 15 14:44:42 n11 sshd[12282]: debug1: monitor_read_log: child log fd closed
Apr 15 14:44:42 n11 sshd[12282]: debug3: mm_request_receive: entering
Apr 15 14:44:42 n11 sshd[12282]: debug1: do_cleanup
Apr 15 14:44:42 n11 sshd[12282]: debug3: PAM: sshpam_thread_cleanup entering
Apr 15 14:44:42 n11 sshd[12282]: debug1: Killing privsep child 12283
Apr 15 14:44:42 n11 sshd[12282]: debug1: audit_event: unhandled event 12
</pre>
</details>

After enabling algorithms `rsa-sha2-512,rsa-sha2-256` with the following code, we get a different exception.
```java
        JSch.setConfig("server_host_key", JSch.getConfig("server_host_key") + ",rsa-sha2-512,rsa-sha2-256");
        JSch.setConfig("PubkeyAcceptedAlgorithms",
                JSch.getConfig("PubkeyAcceptedAlgorithms") + ",rsa-sha2-512,rsa-sha2-256");
```

```
Caused by: com.jcraft.jsch.JSchException: Session.connect: java.security.SignatureException: Signature length not correct: got 404 but was expecting 384
        at com.jcraft.jsch.Session.connect(Session.java:565)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at com.exasol.exasoltestsetup.SshConnection.createSession(SshConnection.java:39)
        ... 7 more
```

<details>
<summary>Server log</summary>
<pre>
Apr 15 14:46:04 n11 sshd[2810]: debug3: fd 5 is not O_NONBLOCK
Apr 15 14:46:04 n11 sshd[2810]: debug1: Forked child 12361.
Apr 15 14:46:04 n11 sshd[2810]: debug3: send_rexec_state: entering fd = 8 config len 3256
Apr 15 14:46:04 n11 sshd[2810]: debug3: ssh_msg_send: type 0
Apr 15 14:46:04 n11 sshd[2810]: debug3: send_rexec_state: done
Apr 15 14:46:04 n11 sshd[12361]: debug3: oom_adjust_restore
Apr 15 14:46:04 n11 sshd[12361]: debug1: Set /proc/self/oom_score_adj to 0
Apr 15 14:46:04 n11 sshd[12361]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Apr 15 14:46:04 n11 sshd[12361]: debug1: inetd sockets after dupping: 4, 4
Apr 15 14:46:04 n11 sshd[12361]: Connection from 172.17.0.1 port 63442 on 172.17.0.3 port 22 rdomain ""
Apr 15 14:46:04 n11 sshd[12361]: debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
Apr 15 14:46:04 n11 sshd[12361]: debug1: Remote protocol version 2.0, remote software version JSCH-0.1.54
Apr 15 14:46:04 n11 sshd[12361]: debug1: compat_banner: no match: JSCH-0.1.54
Apr 15 14:46:04 n11 sshd[12361]: debug2: fd 4 setting O_NONBLOCK
Apr 15 14:46:04 n11 sshd[12361]: debug3: ssh_sandbox_init: preparing seccomp filter sandbox
Apr 15 14:46:04 n11 sshd[12361]: debug2: Network child is on pid 12362
Apr 15 14:46:04 n11 sshd[12361]: debug3: preauth child monitor started
Apr 15 14:46:04 n11 sshd[12361]: debug3: privsep user:group 102:65534 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: permanently_set_uid: 102/65534 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: ssh_sandbox_child: setting PR_SET_NO_NEW_PRIVS [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: ssh_sandbox_child: attaching seccomp filter program [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: append_hostkey_type: ssh-rsa key not permitted by HostkeyAlgorithms [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: send packet: type 20 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: receive packet: type 20 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: SSH2_MSG_KEXINIT received [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: local server KEXINIT proposal [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: compression ctos: none,zlib@openssh.com [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: compression stoc: none,zlib@openssh.com [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: languages ctos:  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: languages stoc:  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: first_kex_follows 0  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: reserved 0  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: peer client KEXINIT proposal [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: host key algorithms: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: ciphers ctos: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: ciphers stoc: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: MACs ctos: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: MACs stoc: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: compression ctos: none [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: compression stoc: none [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: languages ctos:  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: languages stoc:  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: first_kex_follows 0  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: reserved 0  [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: kex: host key algorithm: rsa-sha2-512 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: receive packet: type 30 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: SSH2_MSG_KEX_ECDH_INIT received [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_sshkey_sign: entering [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_send: entering, type 6 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_sshkey_sign: waiting for MONITOR_ANS_SIGN [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_receive_expect: entering, type 7 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_receive: entering [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_receive: entering
Apr 15 14:46:04 n11 sshd[12361]: debug3: monitor_read: checking request 6
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_answer_sign: entering
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_answer_sign: rsa-sha2-512 KEX signature len=404
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_send: entering, type 7
Apr 15 14:46:04 n11 sshd[12361]: debug2: monitor_read: 6 used once, disabling now
Apr 15 14:46:04 n11 sshd[12361]: debug3: send packet: type 31 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: send packet: type 21 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug2: ssh_set_newkeys: mode 1 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: rekey out after 4294967296 blocks [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: receive packet: type 1 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: error: Received disconnect from 172.17.0.1 port 63442:3: java.security.SignatureException: Signature length not correct: got 404 but was expecting 384 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: Disconnected from 172.17.0.1 port 63442 [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: do_cleanup [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug3: PAM: sshpam_thread_cleanup entering [preauth]
Apr 15 14:46:04 n11 sshd[12361]: debug1: monitor_read_log: child log fd closed
Apr 15 14:46:04 n11 sshd[12361]: debug3: mm_request_receive: entering
Apr 15 14:46:04 n11 sshd[12361]: debug1: do_cleanup
Apr 15 14:46:04 n11 sshd[12361]: debug3: PAM: sshpam_thread_cleanup entering
Apr 15 14:46:04 n11 sshd[12361]: debug1: Killing privsep child 12362
Apr 15 14:46:04 n11 sshd[12361]: debug1: audit_event: unhandled event 12
</pre>
</details>

I didn't find a way to fix the signature length problem. Effort until now: 9:30h
